package com.example.backend.storage.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import com.example.backend.auth.entity.AppUser;
import com.example.backend.auth.repository.AppUserRepository;
import com.example.backend.storage.dto.StoredFileResponse;
import com.example.backend.storage.entity.StoredFile;
import com.example.backend.storage.entity.StoredFileStatus;
import com.example.backend.storage.repository.StoredFileRepository;
import io.minio.MinioClient;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

@SpringBootTest
@ActiveProfiles("test")
@TestPropertySource(properties = {
        "spring.datasource.url=jdbc:h2:mem:storage-service-integration;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password=",
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.jpa.open-in-view=false",
        "spring.flyway.enabled=false",
        "app.cors.allowed-origin=http://localhost:4200",
        "app.frontend.base-url=http://localhost:4200",
        "app.jwt.secret=6d8f5b72d2f64f64bca92be8b20ee6aa9fb6a8593d860f72cb1e9d1abf34b821",
        "app.jwt.access-token-expiration-minutes=15",
        "app.jwt.refresh-token-expiration-days=7",
        "app.storage.bucket=boilerplate-files",
        "app.storage.endpoint=http://localhost:9000",
        "app.storage.public-endpoint=http://localhost:9000",
        "app.storage.access-key=minioadmin",
        "app.storage.secret-key=minioadmin"
})
class StorageServiceIntegrationTest {

    @Autowired
    private StorageService storageService;

    @Autowired
    private AppUserRepository appUserRepository;

    @Autowired
    private StoredFileRepository storedFileRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @MockitoBean(name = "internalMinioClient")
    private MinioClient internalMinioClient;

    @MockitoBean(name = "publicMinioClient")
    private MinioClient publicMinioClient;

    @BeforeEach
    void setUpSchema() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS app_user (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(255) NOT NULL UNIQUE,
                    first_name VARCHAR(100) NOT NULL,
                    last_name VARCHAR(100) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    password_hash VARCHAR(255) NOT NULL DEFAULT '',
                    role VARCHAR(50) NOT NULL DEFAULT 'USER',
                    enabled BOOLEAN NOT NULL DEFAULT TRUE,
                    email_verified BOOLEAN NOT NULL DEFAULT FALSE
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS stored_file (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_id BIGINT NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
                    original_filename VARCHAR(255) NOT NULL,
                    content_type VARCHAR(255) NOT NULL,
                    bucket_name VARCHAR(100) NOT NULL,
                    object_key VARCHAR(500) NOT NULL UNIQUE,
                    size_bytes BIGINT,
                    etag VARCHAR(255),
                    status VARCHAR(50) NOT NULL,
                    uploaded_at TIMESTAMP,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
        storedFileRepository.deleteAll();
        appUserRepository.deleteAll();
    }

    @Test
    void findAllForUserMapsLazyOwnerWithOpenInViewDisabled() {
        AppUser owner = appUserRepository.save(buildUser("owner@local.dev", "Jane", "Doe", "USER"));
        StoredFile storedFile = new StoredFile();
        storedFile.setOwner(owner);
        storedFile.setOriginalFilename("guide.pdf");
        storedFile.setContentType("application/pdf");
        storedFile.setBucketName("boilerplate-files");
        storedFile.setObjectKey("users/" + owner.getId() + "/2026/04/guide.pdf");
        storedFile.setSizeBytes(2048L);
        storedFile.setStatus(StoredFileStatus.READY);
        storedFileRepository.saveAndFlush(storedFile);

        List<StoredFileResponse> responses = storageService.findAllForUser("owner@local.dev");

        assertEquals(1, responses.size());
        StoredFileResponse response = responses.getFirst();
        assertEquals("Jane Doe", response.ownerName());
        assertEquals("guide.pdf", response.originalFilename());
    }

    private AppUser buildUser(String email, String firstName, String lastName, String role) {
        AppUser user = new AppUser();
        user.setEmail(email);
        user.setFirstName(firstName);
        user.setLastName(lastName);
        user.setPasswordHash("encoded-password");
        user.setRole(role);
        user.setEnabled(true);
        user.setEmailVerified(true);
        return user;
    }
}
